### ISSUE TITLE
gulp-xml-editor dependency issue, node-gyp build failed with node current LTS 6.x.x 

### ISSUE THREAD

**Issue by krish-dev** [mhartington/gulp-cordova-config#2]
Hi @mhartington 

This node module is very useful for me. 

You have used [gulp-xml-editor](https://github.com/morou/gulp-xml-editor) which is no longer maintain for long. [gulp-xml-editor](https://github.com/morou/gulp-xml-editor) module having a dependency of "libxmljs": "^0.14.0" which is not supported by node latest LTS version. Kindly update the [gulp-xml-editor](https://github.com/morou/gulp-xml-editor) to [gulp-xml-transformer](https://github.com/perrin4869/gulp-xml-transformer) which is well mentained and 100% compatible with [gulp-xml-editor](https://github.com/morou/gulp-xml-editor). Kindly check this issue https://github.com/morou/gulp-xml-editor/issues/14

**Comment by mhartington** [comment]
I have no interest in maintaining this anymore. Please fork and publish your own version.
